name: Deploy Next Version
on:
  push:
    branches:
      - master

concurrency:
  group: "nsite"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Set build env
        run: |
          echo "VITE_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VITE_APP_VERSION=preview" >> $GITHUB_ENV

      - name: Build
        env:
          VITE_TENOR_API_KEY: ${{ secrets.VITE_TENOR_API_KEY }}
          VITE_PAYWALL_NIP05: "/.well-known/nostr.json"
          VITE_PAYWALL_MESSAGE: "This is the latest alpha build of noStrudel.\nIf your enjoying the new features consider supporting the project by donating some sats and adding your message on the support page."
        run: pnpm build

      - name: Redirect 404 to Index for SPA
        run: cp dist/index.html dist/404.html

      - name: Deploy nsite
        run: npx -y nsite-cli upload dist --verbose --purge --privatekey ${{ secrets.NSITE_KEY }}
